global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'b2b-api'
    static_configs:
      - targets: ['qualitygatepoc-app-1:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgresql'
    static_configs:
      - targets: ['qualitygatepoc-oracle-db-1:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['qualitygatepoc-redis-1:6379']

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []